// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name,
    phone
) VALUES (
    $1,
    $2
)
RETURNING
    id,
    full_name,
    phone,
    created_at,
    updated_at
`

type CreateUserParams struct {
	FullName string  `json:"full_name"`
	Phone    *string `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.FullName, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enrichUserFromProvider = `-- name: EnrichUserFromProvider :one
UPDATE users
SET
    full_name = CASE WHEN $1::bool THEN $2 ELSE full_name END,
    phone = CASE WHEN $3::bool THEN $4 ELSE phone END
WHERE id = $5
RETURNING
    id,
    full_name,
    phone,
    created_at,
    updated_at
`

type EnrichUserFromProviderParams struct {
	FullNameSet bool        `json:"full_name_set"`
	FullName    string      `json:"full_name"`
	PhoneSet    bool        `json:"phone_set"`
	Phone       *string     `json:"phone"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) EnrichUserFromProvider(ctx context.Context, arg EnrichUserFromProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, enrichUserFromProvider,
		arg.FullNameSet,
		arg.FullName,
		arg.PhoneSet,
		arg.Phone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT
    u.id,
    u.full_name,
    u.phone,
    u.created_at,
    u.updated_at
FROM user_oauth_accounts ua
INNER JOIN users u ON u.id = ua.user_id
WHERE ua.provider = $1
  AND ua.provider_user_id = $2
`

type GetUserByOAuthParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuth, arg.Provider, arg.ProviderUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT
    id,
    full_name,
    phone,
    created_at,
    updated_at
FROM users
WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByID = `-- name: GetUserProfileByID :one
SELECT
    full_name,
    phone
FROM users
WHERE id = $1
`

type GetUserProfileByIDRow struct {
	FullName string  `json:"full_name"`
	Phone    *string `json:"phone"`
}

func (q *Queries) GetUserProfileByID(ctx context.Context, id pgtype.UUID) (GetUserProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByID, id)
	var i GetUserProfileByIDRow
	err := row.Scan(&i.FullName, &i.Phone)
	return i, err
}

const insertUserOAuthAccount = `-- name: InsertUserOAuthAccount :exec
INSERT INTO user_oauth_accounts (
    user_id,
    provider,
    provider_user_id
) VALUES (
    $1,
    $2,
    $3
)
`

type InsertUserOAuthAccountParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
}

func (q *Queries) InsertUserOAuthAccount(ctx context.Context, arg InsertUserOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, insertUserOAuthAccount, arg.UserID, arg.Provider, arg.ProviderUserID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    full_name = CASE WHEN $1::bool THEN $2 ELSE full_name END,
    phone = CASE WHEN $3::bool THEN $4 ELSE phone END
WHERE id = $5
RETURNING
    id,
    full_name,
    phone,
    created_at,
    updated_at
`

type UpdateUserProfileParams struct {
	FullNameSet bool        `json:"full_name_set"`
	FullName    string      `json:"full_name"`
	PhoneSet    bool        `json:"phone_set"`
	Phone       *string     `json:"phone"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FullNameSet,
		arg.FullName,
		arg.PhoneSet,
		arg.Phone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
