// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEventUser = `-- name: AddEventUser :exec
INSERT INTO event_users (
    event_id,
    user_id,
    role,
    status
) VALUES (
    $1,
    $2,
    'organizer',
    'active'
)
`

type AddEventUserParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddEventUser(ctx context.Context, arg AddEventUserParams) error {
	_, err := q.db.Exec(ctx, addEventUser, arg.EventID, arg.UserID)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    city,
    event_date,
    event_time,
    expected_guest_count,
    budget,
    status
) VALUES (
    $1,
    $2::date,
    $3::time,
    $4,
    $5::numeric,
    'draft'
)
RETURNING
    id,
    city,
    event_date,
    event_time,
    expected_guest_count,
    budget,
    title,
    description,
    status,
    selected_variant_id,
    created_at,
    updated_at
`

type CreateEventParams struct {
	City               string         `json:"city"`
	EventDate          pgtype.Date    `json:"event_date"`
	EventTime          pgtype.Time    `json:"event_time"`
	ExpectedGuestCount int32          `json:"expected_guest_count"`
	Budget             pgtype.Numeric `json:"budget"`
}

type CreateEventRow struct {
	ID                 pgtype.UUID        `json:"id"`
	City               string             `json:"city"`
	EventDate          pgtype.Date        `json:"event_date"`
	EventTime          pgtype.Time        `json:"event_time"`
	ExpectedGuestCount int32              `json:"expected_guest_count"`
	Budget             pgtype.Numeric     `json:"budget"`
	Title              *string            `json:"title"`
	Description        *string            `json:"description"`
	Status             string             `json:"status"`
	SelectedVariantID  pgtype.UUID        `json:"selected_variant_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.City,
		arg.EventDate,
		arg.EventTime,
		arg.ExpectedGuestCount,
		arg.Budget,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.EventDate,
		&i.EventTime,
		&i.ExpectedGuestCount,
		&i.Budget,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.SelectedVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventInvite = `-- name: CreateEventInvite :exec
INSERT INTO event_invites (
    event_id,
    created_by_user_id,
    token,
    title
) VALUES (
    $1,
    $2,
    $3,
    'primary'
)
`

type CreateEventInviteParams struct {
	EventID         pgtype.UUID `json:"event_id"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
	Token           string      `json:"token"`
}

func (q *Queries) CreateEventInvite(ctx context.Context, arg CreateEventInviteParams) error {
	_, err := q.db.Exec(ctx, createEventInvite, arg.EventID, arg.CreatedByUserID, arg.Token)
	return err
}

const getEventAccessRole = `-- name: GetEventAccessRole :one
WITH related AS (
    SELECT eu.role AS access_role, 1 AS priority
    FROM event_users eu
    WHERE eu.event_id = $1
      AND eu.user_id = $2
      AND eu.status = 'active'

    UNION ALL

    SELECT
        CASE
            WHEN eg.approval_status <> 'approved' THEN 'guest_' || eg.approval_status
            WHEN eg.attendance_status = 'confirmed' THEN 'guest_confirmed'
            WHEN eg.attendance_status = 'declined' THEN 'guest_declined'
            ELSE 'guest_approved'
        END AS access_role,
        2 AS priority
    FROM event_guests eg
    WHERE eg.event_id = $1
      AND eg.user_id = $2
)
SELECT access_role
FROM related
ORDER BY priority
LIMIT 1
`

type GetEventAccessRoleParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetEventAccessRole(ctx context.Context, arg GetEventAccessRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getEventAccessRole, arg.EventID, arg.UserID)
	var access_role string
	err := row.Scan(&access_role)
	return access_role, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id,
    city,
    event_date,
    event_time,
    expected_guest_count,
    budget,
    title,
    description,
    status,
    selected_variant_id,
    created_at,
    updated_at
FROM events
WHERE id = $1
`

type GetEventByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	City               string             `json:"city"`
	EventDate          pgtype.Date        `json:"event_date"`
	EventTime          pgtype.Time        `json:"event_time"`
	ExpectedGuestCount int32              `json:"expected_guest_count"`
	Budget             pgtype.Numeric     `json:"budget"`
	Title              *string            `json:"title"`
	Description        *string            `json:"description"`
	Status             string             `json:"status"`
	SelectedVariantID  pgtype.UUID        `json:"selected_variant_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.EventDate,
		&i.EventTime,
		&i.ExpectedGuestCount,
		&i.Budget,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.SelectedVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventWithGuestAccess = `-- name: GetEventWithGuestAccess :one
SELECT
    e.id,
    e.city,
    e.event_date,
    e.event_time,
    e.expected_guest_count,
    e.budget,
    e.title,
    e.description,
    e.status,
    e.selected_variant_id,
    CASE
        WHEN eg.approval_status <> 'approved' THEN 'guest_' || eg.approval_status
        WHEN eg.attendance_status = 'confirmed' THEN 'guest_confirmed'
        WHEN eg.attendance_status = 'declined' THEN 'guest_declined'
        ELSE 'guest_approved'
    END AS access_role,
    eg.approval_status::text,
    eg.attendance_status::text,
    e.created_at,
    e.updated_at
FROM events e
INNER JOIN event_guests eg ON eg.event_id = e.id AND eg.user_id = $1
WHERE e.id = $2
`

type GetEventWithGuestAccessParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	EventID pgtype.UUID `json:"event_id"`
}

type GetEventWithGuestAccessRow struct {
	ID                 pgtype.UUID        `json:"id"`
	City               string             `json:"city"`
	EventDate          pgtype.Date        `json:"event_date"`
	EventTime          pgtype.Time        `json:"event_time"`
	ExpectedGuestCount int32              `json:"expected_guest_count"`
	Budget             pgtype.Numeric     `json:"budget"`
	Title              *string            `json:"title"`
	Description        *string            `json:"description"`
	Status             string             `json:"status"`
	SelectedVariantID  pgtype.UUID        `json:"selected_variant_id"`
	AccessRole         string             `json:"access_role"`
	EgApprovalStatus   string             `json:"eg_approval_status"`
	EgAttendanceStatus string             `json:"eg_attendance_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEventWithGuestAccess(ctx context.Context, arg GetEventWithGuestAccessParams) (GetEventWithGuestAccessRow, error) {
	row := q.db.QueryRow(ctx, getEventWithGuestAccess, arg.UserID, arg.EventID)
	var i GetEventWithGuestAccessRow
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.EventDate,
		&i.EventTime,
		&i.ExpectedGuestCount,
		&i.Budget,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.SelectedVariantID,
		&i.AccessRole,
		&i.EgApprovalStatus,
		&i.EgAttendanceStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT
    id,
    event_id
FROM event_invites
WHERE token = $1
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
`

type GetInviteByTokenRow struct {
	ID      pgtype.UUID `json:"id"`
	EventID pgtype.UUID `json:"event_id"`
}

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (GetInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i GetInviteByTokenRow
	err := row.Scan(&i.ID, &i.EventID)
	return i, err
}

const incrementInviteUsage = `-- name: IncrementInviteUsage :exec
UPDATE event_invites
SET usage_count = usage_count + 1
WHERE id = $1
`

func (q *Queries) IncrementInviteUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementInviteUsage, id)
	return err
}

const listEventLocationsByEventID = `-- name: ListEventLocationsByEventID :many
SELECT
    id,
    event_id,
    variant_id,
    title,
    address,
    contacts,
    ai_comment,
    ai_score,
    sort_order,
    source,
    is_rejected,
    rejected_at,
    created_at,
    updated_at
FROM event_locations
WHERE event_id = $1
ORDER BY variant_id, sort_order, created_at
`

func (q *Queries) ListEventLocationsByEventID(ctx context.Context, eventID pgtype.UUID) ([]EventLocation, error) {
	rows, err := q.db.Query(ctx, listEventLocationsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventLocation
	for rows.Next() {
		var i EventLocation
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.VariantID,
			&i.Title,
			&i.Address,
			&i.Contacts,
			&i.AiComment,
			&i.AiScore,
			&i.SortOrder,
			&i.Source,
			&i.IsRejected,
			&i.RejectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventVariantsByEventID = `-- name: ListEventVariantsByEventID :many
SELECT
    id,
    event_id,
    variant_number,
    title,
    description,
    status,
    llm_request_id,
    generation_error,
    created_at,
    updated_at
FROM event_variants
WHERE event_id = $1
ORDER BY variant_number
`

func (q *Queries) ListEventVariantsByEventID(ctx context.Context, eventID pgtype.UUID) ([]EventVariant, error) {
	rows, err := q.db.Query(ctx, listEventVariantsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventVariant
	for rows.Next() {
		var i EventVariant
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.VariantNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.LlmRequestID,
			&i.GenerationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyEvents = `-- name: ListMyEvents :many
WITH related AS (
    SELECT
        eu.event_id,
        eu.role AS access_role,
        NULL::text AS approval_status,
        NULL::text AS attendance_status,
        1 AS priority
    FROM event_users eu
    WHERE eu.user_id = $1
      AND eu.status = 'active'

    UNION ALL

    SELECT
        eg.event_id,
        CASE
            WHEN eg.approval_status <> 'approved' THEN 'guest_' || eg.approval_status
            WHEN eg.attendance_status = 'confirmed' THEN 'guest_confirmed'
            WHEN eg.attendance_status = 'declined' THEN 'guest_declined'
            ELSE 'guest_approved'
        END AS access_role,
        eg.approval_status::text,
        eg.attendance_status::text,
        2 AS priority
    FROM event_guests eg
    WHERE eg.user_id = $1
)
SELECT DISTINCT ON (e.id)
    e.id,
    e.city,
    e.event_date,
    e.event_time,
    e.expected_guest_count,
    e.budget,
    e.title,
    e.description,
    e.status,
    e.selected_variant_id,
    related.access_role,
    related.approval_status,
    related.attendance_status,
    e.created_at,
    e.updated_at
FROM events e
INNER JOIN related ON related.event_id = e.id
ORDER BY e.id, related.priority, e.created_at DESC
`

type ListMyEventsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	City               string             `json:"city"`
	EventDate          pgtype.Date        `json:"event_date"`
	EventTime          pgtype.Time        `json:"event_time"`
	ExpectedGuestCount int32              `json:"expected_guest_count"`
	Budget             pgtype.Numeric     `json:"budget"`
	Title              *string            `json:"title"`
	Description        *string            `json:"description"`
	Status             string             `json:"status"`
	SelectedVariantID  pgtype.UUID        `json:"selected_variant_id"`
	AccessRole         string             `json:"access_role"`
	ApprovalStatus     *string            `json:"approval_status"`
	AttendanceStatus   *string            `json:"attendance_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMyEvents(ctx context.Context, userID pgtype.UUID) ([]ListMyEventsRow, error) {
	rows, err := q.db.Query(ctx, listMyEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyEventsRow
	for rows.Next() {
		var i ListMyEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.EventDate,
			&i.EventTime,
			&i.ExpectedGuestCount,
			&i.Budget,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.SelectedVariantID,
			&i.AccessRole,
			&i.ApprovalStatus,
			&i.AttendanceStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEventGuestByUser = `-- name: UpsertEventGuestByUser :exec
INSERT INTO event_guests (
    event_id,
    invite_id,
    user_id,
    full_name,
    phone
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (event_id, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET
    invite_id = EXCLUDED.invite_id,
    full_name = EXCLUDED.full_name,
    phone = EXCLUDED.phone,
    updated_at = NOW()
`

type UpsertEventGuestByUserParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	InviteID pgtype.UUID `json:"invite_id"`
	UserID   pgtype.UUID `json:"user_id"`
	FullName string      `json:"full_name"`
	Phone    *string     `json:"phone"`
}

func (q *Queries) UpsertEventGuestByUser(ctx context.Context, arg UpsertEventGuestByUserParams) error {
	_, err := q.db.Exec(ctx, upsertEventGuestByUser,
		arg.EventID,
		arg.InviteID,
		arg.UserID,
		arg.FullName,
		arg.Phone,
	)
	return err
}
