// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// События и статусы генерации
type Event struct {
	ID                 pgtype.UUID    `json:"id"`
	City               string         `json:"city"`
	EventDate          pgtype.Date    `json:"event_date"`
	EventTime          pgtype.Time    `json:"event_time"`
	ExpectedGuestCount int32          `json:"expected_guest_count"`
	Budget             pgtype.Numeric `json:"budget"`
	Title              *string        `json:"title"`
	Description        *string        `json:"description"`
	// draft/generating/ready/failed/cancelled
	Status               string             `json:"status"`
	GenerationStartedAt  pgtype.Timestamptz `json:"generation_started_at"`
	GenerationFinishedAt pgtype.Timestamptz `json:"generation_finished_at"`
	GenerationError      *string            `json:"generation_error"`
	// Ссылка на выбранный пользователем вариант события
	SelectedVariantID pgtype.UUID        `json:"selected_variant_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// RSVP-гости события и их статусы
type EventGuest struct {
	ID       pgtype.UUID `json:"id"`
	EventID  pgtype.UUID `json:"event_id"`
	InviteID pgtype.UUID `json:"invite_id"`
	UserID   pgtype.UUID `json:"user_id"`
	FullName string      `json:"full_name"`
	Phone    *string     `json:"phone"`
	// Решение организатора: pending/approved/rejected
	ApprovalStatus string `json:"approval_status"`
	// Ответ гостя: pending/confirmed/declined
	AttendanceStatus string             `json:"attendance_status"`
	Comment          *string            `json:"comment"`
	PlusOneCount     int32              `json:"plus_one_count"`
	ApprovedByUserID pgtype.UUID        `json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	RespondedAt      pgtype.Timestamptz `json:"responded_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Многоразовые deep-link ссылки на событие
type EventInvite struct {
	ID              pgtype.UUID        `json:"id"`
	EventID         pgtype.UUID        `json:"event_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	Token           string             `json:"token"`
	Title           *string            `json:"title"`
	IsActive        bool               `json:"is_active"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	UsageCount      int32              `json:"usage_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Карточки локаций внутри конкретного сгенерированного варианта
type EventLocation struct {
	ID           pgtype.UUID    `json:"id"`
	EventID      pgtype.UUID    `json:"event_id"`
	VariantID    pgtype.UUID    `json:"variant_id"`
	Title        string         `json:"title"`
	ImageUrl     *string        `json:"image_url"`
	Description  *string        `json:"description"`
	Rating       pgtype.Numeric `json:"rating"`
	Address      *string        `json:"address"`
	WorkingHours *string        `json:"working_hours"`
	AvgBill      *string        `json:"avg_bill"`
	Cuisine      *string        `json:"cuisine"`
	Contacts     *string        `json:"contacts"`
	AiComment    *string        `json:"ai_comment"`
	AiScore      pgtype.Numeric `json:"ai_score"`
	SortOrder    int32          `json:"sort_order"`
	// initial = первая генерация, regenerated = замена после перегенерации
	Source     string             `json:"source"`
	IsRejected bool               `json:"is_rejected"`
	RejectedAt pgtype.Timestamptz `json:"rejected_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Организаторы/со-организаторы внутри события
type EventUser struct {
	ID      pgtype.UUID `json:"id"`
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
	// organizer или co_host
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Сгенерированные варианты сценария/подборки для события
type EventVariant struct {
	ID      pgtype.UUID `json:"id"`
	EventID pgtype.UUID `json:"event_id"`
	// Порядковый номер варианта внутри события
	VariantNumber   int32              `json:"variant_number"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	Status          string             `json:"status"`
	LlmRequestID    *string            `json:"llm_request_id"`
	GenerationError *string            `json:"generation_error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Глобальные аккаунты системы
type User struct {
	ID       pgtype.UUID `json:"id"`
	FullName string      `json:"full_name"`
	// Телефон пользователя в нормализованном формате, если провайдер его отдал
	Phone     *string            `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Связки пользователей с внешними OAuth/SSO-провайдерами
type UserOauthAccount struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	// max сейчас, telegram позже
	Provider string `json:"provider"`
	// Внешний идентификатор пользователя у провайдера
	ProviderUserID string             `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
